### ISSUE TITLE
We need to stop using custom hooks to work with API.

### ISSUE THREAD

**Issue by akichula** [aiecel/crap-advisor#13]
Yes, we shouldn't. Instead of this, let's use Redux. And that's why:

- It's highly maintainable
- Prevent re-renders (so important!)
- God bless immutable store
- Use Redux DevTools to very effectible debugging
- There is no reason to write pieces of custom hooks with no idea how to expand it.
- Feel the power of middlewares

**Comment by aiecel** [comment]
Sold.
